server:
  port: 8089

spring:
  application:
    name: storage-service
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

cloudinary:
  cloud-name: ${CLOUDINARY_CLOUD_NAME}
  api-key: ${CLOUDINARY_API_KEY}
  api-secret: ${CLOUDINARY_API_SECRET}

logging:
  level:
    root: INFO
    com.foodrush.storage: DEBUG
